on:
  push:
  workflow_dispatch: 

jobs:
  schema-sync:
    runs-on: ubuntu-latest
    services:
      postgres:
        # https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
         go run main.go
        env:
          POSTGRES_PASSWORD: postgres
